apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  restartPolicy: Never
  containers:
  - name: persistent-tutorial
    image: "alpine"
    command: ["/bin/sh", "-c", "sleep 1000"]
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","do sleep 20; done"]
